### ISSUE TITLE
Add checks to ensure image and label correspondence 

### ISSUE THREAD

**Issue by vnarayan13** [Radiomics/pyradiomics#18]
Add checks (in base class?):
1) image and label have similar (within tolerance) base pixel spacing
2) image and label have similar origins (does this vary with dimension?)
3) image and label have similar 3-space orientation (space directions in nrrd header?)
4) image and label have similar dimensions (not necessary, but need to somehow check registration)

**Comment by JoostJM** [comment]
In #223, I added some checks (including thoses suggested here). The checks described here are applied by SimpleITK when the bounding box is calculated using the `LabelStatisticsImageFilter`, with tolerance specified in the `ProcessObject`. 

In addition to these checks, also checks some size constraints (can't extract features from a single voxel).

2 points with these checks:

1. checks will fail if ROI is a subvolume of original image. I left it like this, because these should not be encouraged, will represent (hopefully) a minority of cases and to write a check for this will most likely not be very performance efficient (as it requires you to compute min and max bound for both image and mask in realworld coordinates and then check validity)
2. these checks are applied after resampling, as the size constraints are important for the ROI after resampling (otherwise, there still could be a single voxel extraction). This does mean that if there is a mask and image that does not match up before resampling, no error will be thrown, as resampling forces them to the same geometry.

**Comment by JoostJM** [comment]
What would be possible is to use the same `LabelStatisticsImageFilter` during resampling (also requires the bounding box). This would do the geometry check also before resampling...

**Comment by JoostJM** [comment]
resolved by #223
