### ISSUE TITLE
itk::ERROR: LabelStatisticsImageFilter(0x7fcabf404910): Inputs do not occupy the same physical space

### ISSUE THREAD

**Issue by GengboLiu** [Radiomics/pyradiomics#226]
I established the pyradiomics environment on my mac. And it is able to run the sample code PyRadiomics Example.ipynb. However, after I changed the input data into my PET and segmentation file both in nrrd format, I got the error as follow:

RuntimeError: Exception thrown in SimpleITK LabelStatisticsImageFilter_Execute: /scratch/dashboards/SimpleITK-OSX10.6-x86_64-pkg/SimpleITK-build/ITK-prefix/include/ITK-4.10/itkImageToImageFilter.hxx:250:
itk::ERROR: LabelStatisticsImageFilter(0x7fcabf404910): Inputs do not occupy the same physical space! 
InputImage Origin: [-3.4166461e+02, -4.9399991e+02, -1.7890000e+03], InputImage_1 Origin: [-3.4166462e+02, -4.9399990e+02, -1.7890000e+03]
	Tolerance: 4.0638856e-06

My input nrrd file should be correct, they can open in 3D slice. I am not sure what should I change with the code.

**Comment by JoostJM** [comment]
This is a known error due to the small tolerance set by SimpleITK by default. See the [FAQ Section](http://pyradiomics.readthedocs.io/en/latest/faq.html) of the online documentation. You can find more details on this error under question " *When I try to extract features, I get an error stating that image and mask do not occupy the same space* ".

**Comment by JoostJM** [comment]
For resampling the mask to the image coordinate space, as is mentioned as an alternative in the FAQ, an example is provided in `bin\resampleMask.py`

**Comment by GengboLiu** [comment]
Thank you very much for the contribution
