### ISSUE TITLE
Installation failure on Windows

### ISSUE THREAD

**Issue by fedorov** [Radiomics/pyradiomics#283]
As reported by Wei Mu, installation is failing on Windows as shown below:

![image](https://user-images.githubusercontent.com/313942/28938370-e0bea9b8-785b-11e7-9b0e-dba037354c4e.png)

Documentation does not list any special requirements for Windows: http://pyradiomics.readthedocs.io/en/latest/installation.html.

**Comment by JoostJM** [comment]
The error listed here appears to be an issue with the compiler set-up (so not a problem of the pyradiomics code). The traceback appears to be going through a set of python scripts before ending up in one that looks to me to be an interface to cygwin compiler, but then hits a null reference exception on a version check, so maybe because cygwin is not installed, or that python is unable to find it.

I myself compile using microsoft VC, which also has free distributions for python compiling. See [here](https://wiki.python.org/moin/WindowsCompilers).

**Comment by fedorov** [comment]
Note that there are no instructions about compiler set-up in the pyradiomics documentation: http://pyradiomics.readthedocs.io/en/latest/installation.html

![image](https://user-images.githubusercontent.com/313942/29274035-6eab9ea4-80d4-11e7-8d7c-70fe0997bd24.png)

**Comment by JoostJM** [comment]
As of PyRadiomics 2.0, Wheels are automatically built and uploaded for PyRadiomics releases. This removes the need for local compiling.
