### ISSUE TITLE
PET processing

### ISSUE THREAD

**Issue by jacapan** [Radiomics/pyradiomics#315]
Hello everyone,

first of all thank you very much for creating pyradiomics. This is an amazing tool! 
Has anybody experience with applying Pyradiomics to PET-data? 
- Are there any pitfalls to consider? 
- Are there any recommendation regarding the params/setting file. 

Best

**Comment by salimkanoun** [comment]
Hi Jacapan,

I'm currently working on PET application with Radiomics.
We are developing a free and Open source PET/CT viewer (http://petctviewer.org) which generate NIFTI segmentation file that are successfully read by pyRadiomics.

For all Radiomics calculation questions, I'm not from pyRadiomics team so I won't answer your questions about pitfalls or params settings.

But if you are looking a way to segment PET images and send them to pyRadiomics I think it  would be nice to work together.

Salim

**Comment by clarehchao** [comment]
Hi Jacapan,

I did apply pyradiomics to PET images for cross validation of the toolbox
that i made for my work.

I only explored radiomics features including first order stats, shape and
size, and glcm related features. One thing to note is to set the the bin
width appropriately for calculating glcm texture features. I think the
default was set at 25 but works well with CT images. I used 0.1 for a fixed
bin width for SUV converted PET images. It may be different for raw PET
images. I didnt explore wavelet related features, but i can see that it may
take some tweaking of the filters suitable for PET images. Otherwise, i was
able to compute radiomic features from the PET images with a given
segmented VOI.

Hope this help!

Cheers,
Clare
