### ISSUE TITLE
can we load image and mask from memory?

### ISSUE THREAD

**Issue by chansigit** [Radiomics/pyradiomics#316]
The demo code loads an image from a file in disk.
Can I load a image matrix variable (e.g. numpy.array) directly?

**Comment by JoostJM** [comment]
@chansigit, Yes and no. No, you can't load a `numpy.array`, because all image handling between modules in PyRadiomics is done as `SimpleITK.Image`. Only inside the feature classes are they converted to `numpy.array` for calculation. Reason for this is that more information is needed than just the voxel values. It also needs information on spacing, direction and origin.

That being said, you can pass loaded images to pyradiomics. During the loading of the image, it checks whether the passed image/mask is a string (pointing to the file location) or a `SimpleITK.Image`. So if you have intermediate output from some python script and you want to use PyRadiomics to extract features, just pass it as a `SimpleITK.Image` and it should work.

**Comment by chansigit** [comment]
Thank you, I solved the issue using the following method.
`data = np.array(ni_slice.get_data())
sitk_data    = sitk.GetImageFromArray(data)
sitk_data.SetSpacing((float(data_spacing[0]), float(data_spacing[1]), float(data_spacing[2])))`

**Comment by kdk411** [comment]
Hello,

I am performing the same thing as @chansigit , but I am getting no outputs at the moment.

my image data is in the shape of [n_slice, x_dim, y_dim, view] where view is the 3 direction views: axial, sagittal, and coronal. And Yes, it is a 2D images in ndarray at the moment.

Below is my code:

```
`train_dir = '/train/'
val_dir = '/val/'

os.chdir(train_dir)
train_img = np.load('train_img.npy')
train_mask = np.load('train_mask.npy')

extractor = featureextractor.RadiomicsFeaturesExtractor()

extractor.disableAllFeatures()

extractor.enableFeatureClassByName('firstorder')

views = ['x','y','z']
n_slice = train_img.shape[0]
data_spacing = [1,1]

for slice_ind in range(n_slice):

	for view_ind in range(len(views)):
		# pick slice and view
		img_slice = train_img[slice_ind,:,:,view_ind]
		mask_slice = train_mask[slice_ind,:,:,view_ind]

		#convert numpy array into sitk

		sitk_img = sitk.GetImageFromArray(img_slice)
		sitk_img.SetSpacing((float(data_spacing[0]), float(data_spacing[1]) ))
		sitk_mask = sitk.GetImageFromArray(mask_slice)
		sitk_mask.SetSpacing((float(data_spacing[0]), float(data_spacing[1]) ))

		 print(extractor.execute(sitk_img, sitk_mask))`
```

And the output is something like the following:

```
OrderedDict()
OrderedDict()
OrderedDict()
```
And those OrderedDict() are all empty... Any thoughts?
