### ISSUE TITLE
Question for Installation 

### ISSUE THREAD

**Issue by ghzhao1992** [Radiomics/pyradiomics#330]
![image](https://user-images.githubusercontent.com/33625156/34599295-5c3b83c8-f22c-11e7-9af6-59bebf93e78c.png)

**Comment by JoostJM** [comment]
@ghzhao1992, It appears to be an error in your setup of your compiler. This is not PyRadiomics specific, but has to do with your setup of python. Because PyRadiomics has C-extensions, it needs a properly configured compiler. Maybe [this](https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed) can help?

Do you have Visual Studio installed? Which version? It may be missing from your PATH variable.

Also check out [this](http://pyradiomics.readthedocs.io/en/latest/faq.html#during-setup-python-is-unable-to-compile-the-c-extensions) FAQ.

**Comment by ghzhao1992** [comment]
Thank you very much for your reply.
    I installed the visual c++  build tools(2015) to solve the problem " Microsoft Visual C++ 14.0 is required".but now it turns into another situation like this...
   I used the Anaconda which already had a self-contained python(3.5), so why we need to install python here again ?
（I am a rookie~~）

**Comment by JoostJM** [comment]
Ah yes, it's not so much that you need to re-install python, as that your PATH variable is incorrect. In short, it means that your anaconda python just can *find* the compiler and therefore also not use it.

In you windows system variables, is the compiler directory in your PATH variable?

should be something like "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"

**Comment by ghzhao1992** [comment]
I have re-modified the path, as you said, obviously successful!
thank you！
