### ISSUE TITLE
Issue: execute ./example/helloRadiomicsWithSettings.py

### ISSUE THREAD

**Issue by zhenweishi** [Radiomics/pyradiomics#343]
Hi, Developers

I have a problem when I execute ./example/helloRadiomicsWithSettings.py. It seems something wrong with reading params file. Do you have a solution?

Traceback (most recent call last):
  File "helloRadiomicsWithSettings.py", line 99, in <module>
    extractor = featureextractor.RadiomicsFeaturesExtractor(paramsFile)
  File "/home/zhenwei/Documents/pyradiomics-1.3.0/radiomics/featureextractor.py", line 51, in __init__
    self.loadParams(args[0])
  File "/home/zhenwei/Documents/pyradiomics-1.3.0/radiomics/featureextractor.py", line 124, in loadParams
    c = pykwalify.core.Core(source_file=paramsFile, schema_files=[schemaFile], extensions=[schemaFuncs])
  File "/home/zhenwei/.local/lib/python2.7/site-packages/pykwalify/core.py", line 66, in __init__
    raise CoreError(u"Provided source_file do not exists on disk: {0}".format(source_file))
pykwalify.errors.CoreError: <CoreError: error code 3: Provided source_file do not exists on disk: /home/zhenwei/Documents/pyradiomics-1.3.0/examples/exampleSettings\Params.yaml: Path: '/'>

**Comment by JoostJM** [comment]
@zhenweishi, If I'm reading this correct, you're running on either Linux or Mac. It can't find the file because in the path `/home/zhenwei/Documents/pyradiomics-1.3.0/examples/exampleSettings\Params.yaml` there is a `\` just before the end. This is hardcoded as such in `exampleRadiomicsWithSettings.py` and is a path separator in Windows.
To fix this change `\` to `/` in `helloRadiomicsWithSettings.py` L79.

Thank you for bringing this to our attention, we will also fix this in the source code.

**Comment by JoostJM** [comment]
Fixed by c7c5d2e

**Comment by zhenweishi** [comment]
@JoostJM Thanks for your help.
