### ISSUE TITLE
Should I use multiple dcm file to calculate radiomics features?

### ISSUE THREAD

**Issue by lisherlock** [Radiomics/pyradiomics#383]
Hi! 
        Thanks your great project first!  I have a problem by using pyradiomics recently. I really hope you can help me solve it pls!

        The problem is whether I should use multiple dcm file as the data and label to calculate radiomics features.  The multiple dcm file means I convert multiple dcm files to one single dcm file. 
        And i know that just 8bit gray-level dcm files can be calculated by pyradiomics. But i just have RGB dcm files. And i try some ways to convert multiple dcm files to one single 8bit gray-level dcm file , but i failed and i always get RGB files.  
        So if i have to use one single dcm file that be converted from multiple dcm files , can you tell me some ways like softwares?  Thanks a lot!

Looking forward to your reply!!

**Comment by JoostJM** [comment]
#361 is an issue that also dealt with DCM conversion.
In short: PyRadiomics expects a 3D, grayscale image in 1 file. There are multiple conversion programs available, including Slicer, dicom2niix and plastimatch.

If I'm reading it correctly, your problem is 2-fold: you have separate files (dcm) and RGB (not grayscale). If you are able to convert to a single file, also check out [this](https://groups.google.com/forum/#!topic/pyradiomics/QLdD_qEw3PY)  thread on the google groups (it handles usage of png, also RGB image).

**Comment by Sophile** [comment]
Could you tell me how to input DICOM file in pyradiomics？

**Comment by JoostJM** [comment]
See above, you first need to convert them to e.g. niftii or nrrd, which you can then use as input for PyRadiomics.

For conversion, you can try programs such as Slicer, dicom2niix and plastimatch.
