### ISSUE TITLE
Image/Mask geometry mismatch (installed using docker).

### ISSUE THREAD

**Issue by zst1992** [Radiomics/pyradiomics#390]
Thank you very much for this wonderful repository. I have installed pyradiomics using docker. When I use it to extract radiomic features, I met the 'Image/Mask geometry mismatch' error.
code:
`sudo docker run -it -v /:/data radiomics/pyradiomics:CLI /data/.../input.nrrd /data/.../mask.nrrd`
error:
`Image/Mask geometry mismatch. Potential solution: increase tolerance using geometryTolerance, see Documentation:Usage:Customizing the Extraction:Settings:geometryTolerance for more information`

I wonder how to increase the geometry tolerance in the case that I have installed docker pyradiomics.
Thank you very much and looking forward to your reply.

**Comment by fedorov** [comment]
You can enable resampling by adding `correctMask: True` to the settings, see this article: https://pyradiomics.readthedocs.io/en/latest/faq.html?highlight=resample#geometry-mismatch-between-image-and-mask

When you get this error, we advise that you visually examine the mask and image for correspondence, using [3D Slicer](https://slicer.org), for example, to ensure the issue is indeed not due to something more serious.

**Comment by zst1992** [comment]
It works. Thank you very much and have a nice day. (In this case, the pixel spacings of the input and mask images are slightly different)

**Comment by fedorov** [comment]
Great, thanks for confirming!

**Comment by iteachmachines** [comment]
@fedorov  Thanks for the solution.Wasted more than 7 hours in it.Finally worked!
