### ISSUE TITLE
2d_wavelet_features_extract

### ISSUE THREAD

**Issue by Bercy0616** [Radiomics/pyradiomics#398]
Excuse me 
I added "force2d:true and force2Ddimension: 0" in params
When I extracted the features, the features name is [HH.HL,LH,LLL]
LLL????? = =?

I wanna know if the LLL is LL?

paste my code:
params = '...\\exampleCT.yaml'
extractor = featureextractor.RadiomicsFeaturesExtractor(params)
extractor.enableImageTypes(Wavelet={})

result = extractor.execute(ori_file_path, seg_file_path)

**Comment by fedorov** [comment]
Looks like a bug, but I didn't manage to track it down yet... Thank you for your report!

**Comment by JoostJM** [comment]
LLL in this case is indeed LL, why the name is not rendered correctly I do not know, but I'll look into it.

**Comment by BalthasarSchachtner** [comment]
Hi,
the "LLL" is coming from the fact, that the name of the "approximation" is hard coded here:
https://github.com/Radiomics/pyradiomics/blob/2a9fd79520cfc1330f714112bd1eaf7dd63e7ec7/radiomics/imageoperations.py#L706
I came across this issue today since I was wondering why the LL/LLL wavelet decomposition is handled separately? As far as I can see it will be used in the same way as the other combinations of high- and low-pass filters LH/HL/HH (and their 3D companions).

**Comment by JoostJM** [comment]
@BalthasarSchachtner, this has to do with the fact that when you do multi-level wavelet decomposition, generally only the last approximation is returned.
