### ISSUE TITLE
Bounding box of ROI is larger than image space

### ISSUE THREAD

**Issue by Geeks-Sid** [Radiomics/pyradiomics#408]
I've been trying to implement feature extraction with pyradiomics for the following [image](https://drive.google.com/open?id=0B8BKWAEakl8rdUFYZmcyMlVaRmE0RFhyWTg1N05EMWpYN3lJ) and the segmented [output](https://drive.google.com/open?id=0B8BKWAEakl8rT3d2dEE3SWtnbl9RLXdvUkVWWnh1dG15c2I4) .
When i run the command 
`pyradiomics Brats18_CBICA_AAM_1_t1ce_corrected.nii.gz Brats18_CBICA_AAM_1.nii.gz --setting "correctMask:True"` . 
I get the following error.

`Image/Mask geometry mismatch, attempting to correct Mask
Bounding box of ROI is larger than image space:
	ROI bounds (image coordinate space) ((-86.5, 85.5, 80.5), (-114.5, 46.5, 121.5))
	Image Size (240, 240, 155)
Image/Mask correction failed, ROI invalid (not found or outside of physical image bounds)
Case-1_Image: /home/sid/Documents/pyradiomics-master/bin/Brats18_CBICA_AAM_1/Brats18_CBICA_AAM_1_t1ce_corrected.nii.gz
Case-1_Mask: /home/sid/Documents/pyradiomics-master/bin/Brats18_CBICA_AAM_1/Brats18_CBICA_AAM_1.nii.gz
`

I've tried correct mask with other options as well as setting the tolerance high, but nothing seems to work. I have visualized them propelrly without any issues with the [CaPTK]('http://captk.projects.nitrc.org/') tool. Is there something wrong with the mask correction or mask resampling?

**Comment by fedorov** [comment]
Can you please load your image and mask into a tool that is known to account for image orientation and spacing, such as 3D Slicer? I don't know much about the CaPTK tool. Most likely the issue is that the geometry of your mask doesn't match the image.

**Comment by Geeks-Sid** [comment]
Hi @fedorov , yes i have tried it in [3D slicer]('https://www.slicer.org/'), but it does not interpret it at all. That's why i switched to CaPTK. I wish to fix the geometry, that is the major reason why i am trying various methods, but i have failed so far. I have tried improving tolerance, but nothing seems to be working at the moment.

**Comment by JoostJM** [comment]
@Geeks-Sid, I agree with @fedorov, this warning appears to be due to a mismatch in your input. More specifically, the warning message tells you that in terms of your input coordinate space, your segmentation appears to be located betwee -86.5 and -114.5 in the x direction, i.e. completely outside the image. I think in this case this is most likely due to a mismatch in the direction matrix.

For your image, this is the expected (1, 0, 0), (0, 1, 0), (0, 0, 1). For your mask, I suspect it to be (-1, 0, 0), (0, 1, 0), (0, 0, 1), but could not check this, as the link you provided for your segmentation also points to the image. If CapTK ignores this direction, or reads it out differently, that would explain why it works in CapTK.

What exactly does not work in Slicer? I was able to load your image normally. It is possible that you were able to load both the image and the segmentation, but as your segmentation is completely out-of-bounds, it is of course not displayed. You can check this by loading just the segmentation (without the image).

If the direction mismatch is the cause, you can correct this by loading (in python) your image with SimpleITK, forcibly setting the direction to that of the image (im.SetDirection(<Tuple with 9 elements>) and saving the result in a new file.
Be careful when doing this, and check your results.

**Comment by fedorov** [comment]
@Geeks-Sid can you please correctly include the segmentation file? Currently, both of the links you included in the initial post point to the same location.

Something that may not be obvious is that if your image and label show up aligned in "some" tool, it does not necessarily mean your images have correct geometry. For example, if a given tool completely ignores origin/spacing/orientation, and just looks at the image matrices, they will line up even if geometry is initialized completely incorrectly. I don't know much about CaPTK, and how it handles geometry, so I do not have the confidence you can say geometry is correct if your segmentation and image line up in that tool.

**Comment by Geeks-Sid** [comment]
@fedorov @JoostJM  Here are some few of my files. [This]('https://drive.google.com/open?id=1ZZpAti9DXTq8chXs5TrgJ9MvBp3da6en') is the reference file and [This]('https://drive.google.com/open?id=1FptJn9VyyKxrX2xz0O94GkLhgcI8Y92m') is the ground truth for the file and [This]('https://drive.google.com/open?id=13QxofSHvFkE1j3-ko1EA-IWeWJ5S0KN_') is the segmented output that I have generated.

@fedorov As you have mentioned, I don't know how to align them to correct generated ground truth. I have tried image resampling and groundtruth tolerance change, but it doesn't seem to work right. I have tried Slicer with the image and the segmented output for visualization, but it is unable to do so. Such a behaviour is not seen in CaPTK so I am doubtful whether the resampling works or not.

**Comment by fedorov** [comment]
The reference file and the "ground truth" file do not cover the same field of view. Where do those files come from?

**Comment by JoostJM** [comment]
@Geeks-Sid, if you want to repeat my fix, try the following in python: 

```
import SimpleITK as sitk

im = sitk.ReadImage('Brats18_2013_2_1_t1ce_corrected.nii.gz')
ma = sitk.ReadImage('Brats18_2013_2_1.nii.gz')

ma.SetDirection(im.GetDirection())
ma.SetOrigin(im.GetOrigin())

sitk.WriteImage(ma, 'Brats18_2013_2_1_correctedGeomerty.nii.gz', True)
```

This forces the direction and origin of your generated mask to be identical to the direction/origin of your image, but does not swap/change you matrix. Therefore, it aligns up as expected afterwards.

Be careful when using this though! Check you alignment visually to prevent unintended mirroring of your segmentation.

**Comment by fedorov** [comment]
> So I was thinking of adding this solution to the package

@Geeks-Sid I would prefer not to include this into pyradiomics, since it would hide potentially critical issue from the user. If the images are not in the same space, the error should force the user to open them in a viewer and confirm the overlap. Blindly propagating image geometry to the input segmentation mask is not a good idea.

**Comment by JoostJM** [comment]
I agree with @fedorov.

**Comment by yangyunfeng-cyber** [comment]
> ma.SetDirection(im.GetDirection())
> ma.SetOrigin(im.GetOrigin())

if you add these , it still can't work, maybe you need to try add "ma.SetSpacing(im.GetSpacing())" behind.
