### ISSUE TITLE
Pyradiomics on PET image

### ISSUE THREAD

**Issue by zhenweishi** [Radiomics/pyradiomics#444]
Hi, all developers

When I set the binWidth for imagetype like
"imageType:
  Original: 
    binWidth: 0.5"
I got the following errors:

![pet_error](https://user-images.githubusercontent.com/17007301/48474427-d4090000-e7fa-11e8-956a-6ac38785e7d6.PNG)

So my questions are: 1) how to solve this issue 2) what is the proper binWidth for PET images.
Looking forward to your reply.

**Comment by JoostJM** [comment]
This error is caused when the size of GLCM would exceed int32 max value, which is generally caused by a too-small binwidth.

You can check this by running just firstorder (without features Uniformity and Entropy), which will provide you with the range of gray values encountered in your image.

As to the best bin width, there is no definitive answer, but there are several threads about that in the issues and on the google groups.

Finally, did you convert your PET images to SUV values? If the input is raw PET data (Bql) a bin width of .5 would be much too small. However in case of SUV, .5 shouldn't be that bad.
