### ISSUE TITLE
Pywavelet >0.4.0 implementation

### ISSUE THREAD

**Issue by BBeuker** [Radiomics/pyradiomics#454]
Is there any chance the pywavelet implementation for getWaveletImage will be expanded to higher versions than 0.4.0? Version 0.5.0 (current version is 1.1.0) adds some pretty interesting wavelets that have shown promising results in Radiomics research.

Or is there another solution for me to implement the pywavelet 0.5.0 and above filters? Thanks for the help!

**Comment by BBeuker** [comment]
Thanks for the help and quick answers Joost, got it up and running but the morlet wavelet seems to lead to some issues due to being 1D Continuous Wavelet instead of discrete. Which logically doesn't work with the stationary wavelet transform, pywavelets also doesn't support 2D CWT so unfortunately it seems like this is not gonna work. Thanks anyway!

**Comment by JoostJM** [comment]
You can try to do it outside of PyRadiomics and build SimpleITK images out of it (`sitk.GetImageFromArray`), remember to copy the direction, and update origin and spacing (twice the spacing of the original image).  Size should automatically be half that of the original image.

The reason you need to update the origin is because origin is defined as the center of the corner voxel, which moved due to the change in spacing. In `imageoperations.py`, I implemented some code for doing things like this in the function for resampling images.

You can then pass that image object instead of a string specifing the image path and extract features that way...

Last note. you don't have to update the mask, but set `correctMask` to True. This will tell PyRadiomics to resample the mask to the image geometry (i.e. half the size, twice the spacing).

**Comment by BBeuker** [comment]
That's great! Didn't think of this option, thank you again will try it this way.
