### ISSUE TITLE
mask file question

### ISSUE THREAD

**Issue by toddcreasy** [Radiomics/pyradiomics#469]
Hi,

First time user to image analysis and processing. I've used both dcm2niix as well as 3DSlicer to export dicom images to imaging formats that pyradiomics can use. However, it's not clear to me from the documentation what the "mask file" that must be included when running the utility.

I'm using DICOM image files from https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI

Thanks

**Comment by JoostJM** [comment]
The mask file is an image with the same size/geometry as the input image you've obtained from the DICOM image files. However, instead of pixel intensities, values of the individual pixels denote to which region of interest the corresponding pixel belongs, by assigning it a label value. Value of '0' denotes background (no ROI).

See also [here on the slicer wiki](https://www.slicer.org/wiki/Modules:Editor-Documentation): 
> *label map volume* is a 3D scalar volume node where each voxel is a number indicating the type of tissue at that location. A label volume is associated with a Color Node that maps the numbers into colors and text strings.

These mask files are needed to allow PyRadiomics to determine which voxels should be part of the calculation of the features and which should be ignored.

**Comment by JoostJM** [comment]
For further reading, I can recommend the [IBSI document](https://arxiv.org/pdf/1612.07003.pdf), which details a lot of the steps for Radiomic feature extraction (section 2.3 details segmentation).

Moreover, this paper gives a very nice overview of Radiomics and the challenges that may arrise:
Kumar V, Gu Y, Basu S, et al. Radiomics: the process and the challenges. Magn Reson Imaging. 2012;30(9):1234-1248. doi:10.1016/j.mri.2012.06.010.

**Comment by fedorov** [comment]
Specifically for the LIDC collection, it is already accompanied by the segmentations ("masks") of the nodules. Those are available in multiple representations, and you can learn more details from this preprint: 

Fedorov A, Hancock M, Clunie D, Brochhausen M, Bona J, Kirby J, Freymann J, Pieper S, Aerts H, Kikinis R, Prior F. 2018. Standardized representation of the LIDC annotations using DICOM. PeerJ Preprints 6:e27378 https://doi.org/10.7287/peerj.preprints.27378
