### ISSUE TITLE
Question about calculation of major/minor/least axis length in Shape features

### ISSUE THREAD

**Issue by mangguoxia** [Radiomics/pyradiomics#485]
Why the principal component analysis can give a 3D axis length? Actually, when rotate the object, the result of least axis length is not correct. Does anyone known that？

**Comment by mangguoxia** [comment]
@JoostJM

**Comment by JoostJM** [comment]
@manguoxia, the PCA analysis does not give the 3D axis length. Rather, it is related to the axes of the enclosing ellipsoid.

I'm afraid I do not fully understand your question about rotation. What do you mean by "least axis length is not correct", what do you define as "correct"?

**Comment by mangguoxia** [comment]
> I'm afraid I do not fully understand your question about rotation. What do you mean by "least axis length is not correct", what do you define as "correct"?

Thank you for your reply ! 
I generated a standard ellipsoid with three axis lengths of 60, 40 and 20, respectively.
I calculated the three axis length, the results are: major 53.63 /  minor 35.76 / and least 17.78
Then it is rotated at an angle(45° along X axis) in space.
After rotated the ellipsoid, I calculated the three axis length again, but I got a different result:
major 65.25 /  minor 52.41 / and least 43.49
I'm confused about that.I think the results should be consistent.

**Comment by mangguoxia** [comment]
The unit of the ellipsoid  is pixels. It's isotropic volume. The size of the image is 150*150*150 .
The ellipsoid has three axis lengths of 60, 40 and 20, respectively. I didn't consider the spacing of the image when generating the ellipsoid, just in pixel.
The images are saved with raw binary format.

[data.zip](https://github.com/Radiomics/pyradiomics/files/3159979/data.zip)

**Comment by JoostJM** [comment]
@mangguoxia, Can you share the code you used to arrive at your results? I attempted to replicate your inconsistencies, but was unable to. 

Here's what I did:

I first loaded the raw data file as a numpy array, and then stored them as NRRD images (PyRadiomics does not accept Numpy Arrays as input, as it requires geometric information.

When I then extract the shape features with PyRadiomics, I obtain very similar results for both the original and the rotated one (some small differences exist, but this is most likely due to rounding and machine precision errors).

Here is the code I used to load your data:
```
import numpy as np
import SimpleITK as sitk

arr = np.fromfile('ellipsoid.raw',  'int16')
arr.reshape((150, 150, 150))
im = sitk.GetImageFromArray(arr)  # results in pixel spacing (1.0, 1.0, 1.0)

sitk.WriteImage('ellipsoid.nrrd', arr, True)

arr_rot = np.fromfile('ellipsoidRotated.raw',  'int16')
arr_rot.reshape((150, 150, 150))
im_rot = sitk.GetImageFromArray(arr_rot)  # results in pixel spacing (1.0, 1.0, 1.0)

sitk.WriteImage('ellipsoidRotated.nrrd', arr_rot, True)
```

I then used PyRadiomics command line to extract features with parameters:
```
featureClass:
  shape:
    - Maximum3DDiameter
    - MajorAxisLength
    - MinorAxisLength
    - LeastAxisLength

imageType:
  Original: {}
```

`pyradiomics ellipsoidRotated.nrrd ellipsoidRotated.nrrd -p params.yml`
`pyradiomics ellipsoid.nrrd ellipsoid.nrrd -p params.yml`

Alternatively, you can do it interactively:
```
from radiomics.featureextractor import RadiomicsFeatureExtractor

extractor = RadiomicsFeatureExtractor('params.yml')
featurevector = extractor.execute(im, im)  # you can use the data both as image and mask, as only mask is used for calculation

featurevector_rot = extractor.execute(im_rot, im_rot)
```


This yields the following results:

feature | ellipsoid | ellipsoid_rotated
--------|-----------|-------------------
Maximum3DDiameter | 61.0 | 60.828
MajorAxisLength | 53.638 | 53.750
MinorAxisLength | 35.768 | 35.746
LeastAxisLength | 17.788 | 17.772

**Comment by JoostJM** [comment]
@mangguoxia, as to the reason why the maximum 3D diameter is about 61, instead of 60: This is due to how PyRadiomics sees the volume. Using a marching cubes algorithm, it constructs a triangel mesh representing the hull of the shape. The points of the triangles are always halfway between a voxel that is part of the mask and one that is not. Therefore, the edges is `.5 x spacing` higher and lower that the outer most voxels along your axis of 60 pixels. Given the spacing of 1.0, this results in `60 x 1.0 + 2 x 0.5 x 1.0 = 61`. The reason we use this triangle mesh is that we can use it for approximations of maximum diameters, volume and surface area. We opted to use one approximation to calculate all these values, instead of e.g. voxel centers for diameter, but mesh for surface and then voxels volume for volume calculation. (N.B. PyRadiomics does implement the volume as no. of voxels times volume of a single voxel, but this is for comparison to volume calculation in current general practice. Shape features are based on mesh volume where applicable.

**Comment by mangguoxia** [comment]
@JoostJM  Thank you for your reply!
I am very sorry that my mistake led to the wrong result.
But i find a new method to get a more accurate result of Major/Minor/Least length.
In my image, the results are 60.103 39.609 20.0 .
Here is the code https://github.com/joe-of-all-trades/regionprops3/blob/master/regionprops3.m
The difference is the usage of eigen vectors.
I think you can try this method to get a more accurate method.
And here is the similar information of this method.(The most voted answer)
https://math.stackexchange.com/questions/207685/how-to-find-the-minimal-axis-parallel-ellipse-enclosing-a-set-of-points
Thank you so much！
