### ISSUE TITLE
correspondence of the image and label format 

### ISSUE THREAD

**Issue by cpuxzb** [Radiomics/pyradiomics#488]
can i use the ‘.dcm’ of the image and the ‘.nrrd’ of mask？

**Comment by JoostJM** [comment]
@cpuxzb, depends on your type of data. If your .dcm image is the only image file then yes. If it's part of a series consisting of multiple slices then you'll have to first convert your dicom series to a single-file format like niftii or nrrd (you could use dcm2niix for this).

PyRadiomics supports the image formats supported by SimpleITK. In fact, it reads the files separately and stores it in SimpleITK.Image objects. So long as the mask is contained within the image bounds, you can extract features.

**Comment by destinybuilt** [comment]
> @cpuxzb, depends on your type of data. If your .dcm image is the only image file then yes. If it's part of a series consisting of multiple slices then you'll have to first convert your dicom series to a single-file format like niftii or nrrd (you could use dcm2niix for this).
> 
> PyRadiomics supports the image formats supported by SimpleITK. In fact, it reads the files separately and stores it in SimpleITK.Image objects. So long as the mask is contained within the image bounds, you can extract features.

But I did not see support for the dicom format in the official documentation of SimpleITK.

**Comment by pieper** [comment]
Right, Joost is saying you use a tool like dcm2niix to convert dicom to
something SimpleITK can read.

**Comment by cpuxzb** [comment]
> @cpuxzb，取决于您的数据类型。如果您的.dcm图像是唯一的图像文件，那么是。如果它是由多个切片组成的系列的一部分，那么你必须首先将你的dicom系列转换为单文件格式，如niftii或nrrd（你可以使用dcm2niix）。
> 
> PyRadiomics支持SimpleITK支持的图像格式。实际上，它分别读取文件并将其存储在SimpleITK.Image对象中。只要掩码包含在图像边界内，就可以提取特征。

Thank you for your reply.It‘s very helpful to me，i will try it.

**Comment by JoostJM** [comment]
@cpuxzb, the `xxxx_image.nii` file is the one that goes into "Image" input, and `xxxx_label.nii` file goes into "Mask" input. PyRadiomics actually requires you to have a single image file AND and single mask file to extract features. Combined with the label parameter ("Label" input) (identifying which voxels in the mask file indicate the desired ROI), this represents one "case".

In batch mode, multiple cases can be extracted using multithreading. Cases can be e.g. 
- 1 image file with multiple mask files (1 file per case of course)
- 1 image, 1 mask, but different values for the label 
  - i.e. multiple ROIs in a single mask file
- multiple image files with one mask file
  - e.g. single ROI, multiple sequences
  - each file should define a physical space that contains the entire mask --> NOT multiple files that define 1 region (such as dicom, with each file storing a single slice)
- multiple image files with multiple mask files (e.g. multiple patients)

**Comment by JoostJM** [comment]
@destinybuilt, @pieper, As far as I know SimpleITK does read DICOM files without issue, even if it doesn't have the '.dcm' extension (I assume it checks the DICM preamble in the file to check if it's a valid dicom). However, this can only read a single file at a time and therefore should not be used for reading 3D volumes.

Moreover, SimpleITK does also have a dicom series reader, where you can pass a list of dicom files, but this code does not support the ordering of slices based on direction and image posisition (patient), which is the official DICOM way of ordering slices, which is why we prefer alternative conversion tools.

**Comment by pieper** [comment]
There is code in [ITK](https://itk.org/Doxygen/html/classitk_1_1GDCMSeriesFileNames.html
), to do some sorting of dicom files by position and orientation, and it's [exposed in SimpleITK](https://simpleitk.readthedocs.io/en/master/Examples/DicomSeriesReadModifyWrite/Documentation.html).  But it only handles some general cases, like an equally spaced set of CT slices.  So it can be very confusing for users if their data doesn't conform.  That's why we typically suggest people get comfortable with their acquisitions, e.g. by looking at them in Slicer and then use a batch conversion using dcm2niix.
