### ISSUE TITLE
 ImportError: cannot import name 'deprecated' 

### ISSUE THREAD

**Issue by mehdializade** [Radiomics/pyradiomics#499]
Hi everybody. I have an error in "hellofeatureclass": ImportError: cannot import name 'deprecated' ...

**Comment by mehdializade** [comment]
Hi everybody. I have a error in "hellofeatureclass": ImportError: cannot import name 'deprecated' ...

**Comment by JoostJM** [comment]
Can you add a stack trace? 'deprecated' is not used in helloFeatureClass directly.

It is defined in the `radiomics` global namespace.
So, `from radiomics import deprecated` should work.

Still, in the past we have had similar issues from users, where e.g. `from radiomics import featureextractor` failed. This was due to these users having a different python package named `radiomics` installed.

**Comment by mehdializade** [comment]
Thank you for your help.
The problem was solved by installing "get-pip.py" and update numpy.
