### ISSUE TITLE
Resampling for 2D network

### ISSUE THREAD

**Issue by samra-irshad** [Radiomics/pyradiomics#625]
**Describe the bug**
hi, my post is not about bug but rather image resampling. I have 3D MRI data and I am trying to train it using a 2D network. I need to know if I am training on 2D network, is it compulsory to resample the scans?

**Comment by jvanlunenburg** [comment]
You're talking about using a convolutional neural network with 2D images input?  By resample do you mean spatial resizing?

And most importantly: how is any of this related to pyradiomics?

**Comment by JoostJM** [comment]
This issue is specific about resampling for use in CNN's. In PyRadiomics, resampling is done using SimpleITK. Whether or not to resample for use in CNN's is beyond the scope of PyRadiomics.

A better place to ask this question is a deep learning forum or, if the question is specific to resampling, a SimpleITK forum.
